### PR TITLE
Switch to ed25519-consensus

### PR DESCRIPTION
**Pull request by madninja**

### CODE REVIEW

**Comment by JayKickliter** [comment]
So this is a mostly mechanical switch to a different ED25519 library? Any interesting motivation for the switch? I am fine with the change regardless

**Comment by madninja** [comment]
> So this is a mostly mechanical switch to a different ED25519 library? Any interesting motivation for the switch? I am fine with the change regardless

Yeah, the reasoning is that ed25519-dalek hasn't updated in quite some time, causing collisions/duplicates with shared deps. This makes us have to rely on a fork of it, which means we can't push this crate to crates.io. Using the alternate wrapper around curve25519 gets us back there. 

I've tested this with about 5k wallet addresses so far without issue.

**Review by JayKickliter — APPROVED** [review]
I've read the diff several times and see no issues

**Comment by madninja** [comment]
Made redundant by #37

**Pull request closed without merging**
